// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoVoting.Infrastructure.DbContext;

#nullable disable

namespace NeoVoting.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901050528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Governorate")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Candidates", t =>
                        {
                            t.HasCheckConstraint("CK_Candidate_Gender", "[Gender] IN ('M', 'F')");

                            t.HasCheckConstraint("CK_Candidate_Governorate", "([Governorate] IN (1, 2, 3, 4, 5) )");
                        });
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NominationReasons")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProfilePhotoFilename")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId", "CandidateId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NominationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NominationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VotingStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Elections", t =>
                        {
                            t.HasCheckConstraint("CK_Election_NominationDates", "[NominationEndDate] > [NominationStartDate]");

                            t.HasCheckConstraint("CK_Election_Status", "([Status] IN (1, 2, 3) )");

                            t.HasCheckConstraint("CK_Election_VotingAfterNomination", "[VotingStartDate] >= [NominationEndDate]");

                            t.HasCheckConstraint("CK_Election_VotingDates", "[VotingEndDate] > [VotingStartDate]");
                        });
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ElectionStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualFemaleVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActualMaleVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActualVotersAged18To29Count")
                        .HasColumnType("int");

                    b.Property<int?>("ActualVotersAged30To45Count")
                        .HasColumnType("int");

                    b.Property<int?>("ActualVotersAged46To64Count")
                        .HasColumnType("int");

                    b.Property<int?>("ActualVotersAged65AndOverCount")
                        .HasColumnType("int");

                    b.Property<double?>("DifferenceBetweenMaleAndFemaleActualVoterSharePercentage")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenMaleAndFemaleNominatedCandidateSharePercentage")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenMaleAndFemaleWinningCandidateSharePercentage")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenWinningMaleShareAndActualMaleVoterShare")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenWinningShareAndActualVoterShareForAged18To29")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenWinningShareAndActualVoterShareForAged30To45")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenWinningShareAndActualVoterShareForAged46To64")
                        .HasColumnType("float");

                    b.Property<double?>("DifferenceBetweenWinningShareAndActualVoterShareForAged65AndOver")
                        .HasColumnType("float");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int?>("Governorate")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedCandidatesAged18To29Count")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedCandidatesAged30To45Count")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedCandidatesAged46To64Count")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedCandidatesAged65AndOverCount")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedFemaleCandidatesCount")
                        .HasColumnType("int");

                    b.Property<int?>("NominatedMaleCandidatesCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ParliamentEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ParliamentStartDate")
                        .HasColumnType("date");

                    b.Property<double?>("PercentageOfRegisteredFemaleVotersWhoAreActualFemaleVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfRegisteredMaleVotersWhoAreActualMaleVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfRegisteredVotersAged18To29WhoAreActualVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfRegisteredVotersAged30To45WhoAreActualVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfRegisteredVotersAged46To64WhoAreActualVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfRegisteredVotersAged65AndOverWhoAreActualVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreAged18To29")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreAged30To45")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreAged46To64")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreAged65AndOver")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreFemale")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalActualVotersWhoAreMale")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreAged18To29")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreAged30To45")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreAged46To64")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreAged65AndOver")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreFemale")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalNominatedCandidatesWhoAreMale")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalRegisteredVotersWhoAreActualVoters")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreAged18To29")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreAged30To45")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreAged46To64")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreAged65AndOver")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreFemale")
                        .HasColumnType("float");

                    b.Property<double?>("PercentageOfTotalWinningCandidatesWhoAreMale")
                        .HasColumnType("float");

                    b.Property<int?>("RegisteredFemaleVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredMaleVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVotersAged18To29Count")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVotersAged30To45Count")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVotersAged46To64Count")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVotersAged65AndOverCount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalActualVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalNominatedCandidatesCount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRegisteredVotersCount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalWinningCandidatesCount")
                        .HasColumnType("int");

                    b.Property<int?>("WinningCandidatesAged18To29Count")
                        .HasColumnType("int");

                    b.Property<int?>("WinningCandidatesAged30To45Count")
                        .HasColumnType("int");

                    b.Property<int?>("WinningCandidatesAged46To64Count")
                        .HasColumnType("int");

                    b.Property<int?>("WinningCandidatesAged65AndOverCount")
                        .HasColumnType("int");

                    b.Property<int?>("WinningFemaleCandidatesCount")
                        .HasColumnType("int");

                    b.Property<int?>("WinningMaleCandidatesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("Election_Statistics");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ElectionWinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("ElectionWinners");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.EventParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ElectionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PollId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PollId");

                    b.HasIndex("VoterId", "ElectionId")
                        .IsUnique()
                        .HasFilter("[ElectionId] IS NOT NULL");

                    b.HasIndex("VoterId", "PollId")
                        .IsUnique()
                        .HasFilter("[PollId] IS NOT NULL");

                    b.ToTable("EventParticipations");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Polls", t =>
                        {
                            t.HasCheckConstraint("CK_Poll_StartEndDates", "[EndDate] > [StartDate]");

                            t.HasCheckConstraint("CK_Poll_Status", "([Status] IN (1, 2, 3) )");
                        });
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("PollAnswers");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualVotersCount")
                        .HasColumnType("int");

                    b.Property<double?>("ParticipationPercentage")
                        .HasColumnType("float");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVotersCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId")
                        .IsUnique();

                    b.ToTable("Poll_Statistics");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PollAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PollAnswerId");

                    b.HasIndex("PollId");

                    b.HasIndex("Id", "PollAnswerId")
                        .IsUnique();

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SystemAuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_SystemAuditLog_ActionType", "[ActionType] IN ('ADMIN_CREATED_ELECTION', 'ADMIN_STARTED_VOTING_PHASE', 'ADMIN_ENDED_VOTING_PHASE', 'ADMIN_CREATED_POLL', 'ADMIN_STARTED_POLL', 'ADMIN_ENDED_POLL', 'ADMIN_BANNED_USER_ACCOUNT', 'ADMIN_RESET_USER_PASSWORD')");
                        });
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("Governorate")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("Votes", t =>
                        {
                            t.HasCheckConstraint("CK_Vote_Governorate", "([Governorate] IN (1, 2, 3, 4, 5) )");
                        });
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.VoteChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("VoteId", "CandidateProfileId")
                        .IsUnique();

                    b.ToTable("VoteChoices");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Governorate")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Voters", t =>
                        {
                            t.HasCheckConstraint("CK_Voter_Gender", "[Gender] IN ('M', 'F')");

                            t.HasCheckConstraint("CK_Voter_Governorate", "([Governorate] IN (1, 2, 3, 4, 5) )");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("NeoVoting.Domain.Entities.Candidate", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CandidateProfiles")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.Election", "Election")
                        .WithMany("CandidateProfiles")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ElectionStatistics", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Election", "Election")
                        .WithMany("ElectionStatisticsList")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ElectionWinner", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithOne("ElectionWinner")
                        .HasForeignKey("NeoVoting.Domain.Entities.ElectionWinner", "CandidateProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.EventParticipation", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Election", "Election")
                        .WithMany("EventParticipations")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.Poll", "Poll")
                        .WithMany("EventParticipations")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.Voter", "Voter")
                        .WithMany("EventParticipations")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Poll");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollAnswer", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Poll", "Poll")
                        .WithMany("PollAnswers")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollStatistics", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Poll", "Poll")
                        .WithOne("PollStatistics")
                        .HasForeignKey("NeoVoting.Domain.Entities.PollStatistics", "PollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollVote", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.PollAnswer", "PollAnswer")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollAnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.Poll", "Poll")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("PollAnswer");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Vote", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.VoteChoice", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("VoteChoices")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoVoting.Domain.Entities.Vote", "Vote")
                        .WithMany("VoteChoices")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Voter", b =>
                {
                    b.HasOne("NeoVoting.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Voter")
                        .HasForeignKey("NeoVoting.Domain.Entities.Voter", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateProfiles");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.CandidateProfile", b =>
                {
                    b.Navigation("ElectionWinner");

                    b.Navigation("VoteChoices");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Election", b =>
                {
                    b.Navigation("CandidateProfiles");

                    b.Navigation("ElectionStatisticsList");

                    b.Navigation("EventParticipations");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Poll", b =>
                {
                    b.Navigation("EventParticipations");

                    b.Navigation("PollAnswers");

                    b.Navigation("PollStatistics");

                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.PollAnswer", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Vote", b =>
                {
                    b.Navigation("VoteChoices");
                });

            modelBuilder.Entity("NeoVoting.Domain.Entities.Voter", b =>
                {
                    b.Navigation("EventParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
