using FluentValidation;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using GovernmentSystem.API.Domain.Contracts;
using GovernmentSystem.API.Domain.Entities;
using GovernmentSystem.API.Domain.RepositoryContracts;
using GovernmentSystem.API.Infrastructure.DbContext;
using GovernmentSystem.API.Infrastructure.Repositories;


namespace GovernmentSystem.API.StartupExtensions
{
    public static class ConfigureServicesExtension
    {
        public static IServiceCollection ConfigureServices(this IServiceCollection services,
            IConfiguration configuration, ConfigureHostBuilder configureHostBuilder)
        {
            services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
            {
                options.Password.RequireDigit = true;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireNonAlphanumeric = false; // Set to false if you want to allow only letters and digits
                options.Password.RequiredLength = 4;
                options.Password.RequiredUniqueChars = 1; // You can increase for stricter policy
            })

                .AddEntityFrameworkStores<ApplicationDbContext>()

                .AddDefaultTokenProviders()


                ;

            // The two lines below are unnecessary. The `.AddEntityFrameworkStores<TContext>()`
            // call you made above ALREADY registers these for you.
            // You are explicitly re-registering the exact same default implementations.
            /*
               .AddUserStore<UserStore
               <ApplicationUser, ApplicationRole, ApplicationDbContext, Guid>>()
               //Repository for Users generated by EF automatically
               .AddRoleStore<RoleStore
               <ApplicationRole, ApplicationDbContext, Guid>>()
               ;
            */



            // Get the connection string from appsettings.json
            var connectionString = configuration.GetConnectionString("DefaultConnection")
                ?? throw new InvalidOperationException
                ("Connection string 'DefaultConnection' not found.");

            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseSqlServer(connectionString);
            });


            // --- REGISTER THE UNIT OF WORK ---
            // We use AddScoped for the lifetime. This means a single instance of UnitOfWork
            // (and therefore ApplicationDbContext) is created for each HTTP request. This is the standard.
            services.AddScoped<IUnitOfWork, UnitOfWork>();

            // --- REGISTER REPOSITORIES ---

            services.AddScoped<ICandidateRepository, CandidateRepository>();
            services.AddScoped<IVoterRepository, VoterRepository>();
           

            //services.AddValidatorsFromAssembly(Assembly.Load("GovernmentSystem.API.Application"));


            return services;
        }
    }
}
