using System.Text;

namespace NeoVoting.Domain.Entities
{
    /// <summary>
    /// Represents an immutable, publicly visible log entry for a single vote cast.
    /// This is designed for transparency and auditing, recording the event of a vote
    /// without linking to the voter or their specific choices.
    /// </summary>
    public class PublicVoteLog
    {
        public long Id { get; private set; }
        public DateTime TimestampUTC { get; private set; }

        public string ErrorMessage { get; private set; } = string.Empty;

        // --- Foreign Keys & Navigation Properties ---

        public Guid ElectionId { get; private set; }
        public Election Election { get; private set; }

        public int GovernorateId { get; private set; }
        public Governorate Governorate { get; private set; }

        // 1. Keep the ID Required (Guid, not Guid?)
        // This ensures the Database Column is NOT NULL.
        public Guid VoteId { get; private set; }

        // 2. Make the Navigation Nullable (Vote?)
        // This admits that "Even though the ID exists, the Object might be hidden/deleted."
        public Vote? Vote { get; private set; } // <--- Changed to nullable

        private PublicVoteLog()
        {
            // 3. Remove "Vote = null!;"
            // We don't need to force it anymore because it is allowed to be null.
            Election = null!;
            Governorate = null!;
        }

        // --- Factory Method ---

        /// <summary>
        /// Creates a new PublicVoteLog instance to record the occurrence of a vote.
        /// </summary>
        /// <param name="voteId">The ID of the vote being logged.</param>
        /// <param name="electionId">The ID of the election the vote belongs to.</param>
        /// <param name="governorateId">The ID of the governorate where the vote was cast.</param>
        /// <returns>A new, valid PublicVoteLog object.</returns>
        /// <exception cref="ArgumentException">Thrown if validation fails.</exception>
        public static PublicVoteLog Create(Guid voteId, Guid electionId, int governorateId, string? errorMessage)
        {
            Validate(voteId, electionId);

            var logEntry = new PublicVoteLog
            {
                // The 'Id' is generated by the database.
                VoteId = voteId,
                ElectionId = electionId,
                GovernorateId = governorateId,
                TimestampUTC = DateTime.UtcNow, // The timestamp is always set at the moment of creation.
                ErrorMessage = errorMessage ?? string.Empty
            };

            return logEntry;
        }

        /// <summary>
        /// Private helper method to validate the foreign keys.
        /// </summary>
        private static void Validate(Guid voteId, Guid electionId)
        {
            var errors = new StringBuilder();

            if (voteId == Guid.Empty)
            {
                errors.AppendLine("VoteId is required for the log entry.");
            }

            if (electionId == Guid.Empty)
            {
                errors.AppendLine("ElectionId is required for the log entry.");
            }

            if (errors.Length > 0)
            {
                throw new ArgumentException(errors.ToString());
            }
        }
    }
}