using NeoVoting.Domain.Enums; 
using NeoVoting.Domain.IdentityEntities;
using System.Text;

namespace NeoVoting.Domain.Entities
{
    /// <summary>
    /// Represents an immutable log entry for a significant action in the system. 
    /// This is crucial for security, auditing, and tracking changes.
    /// </summary>
    public class SystemAuditLog 
    {
        public long Id { get; private set; }
        public DateTime TimestampUTC { get; private set; }

        // CHANGED: The ActionType is now a strongly-typed enum.
        public SystemActionTypesEnum ActionType { get; private set; }

        public string? Details { get; private set; }

        // --- Foreign Key & Navigation Property ---

        public Guid? UserId { get; private set; } // The ID of the user who performed the action.
        public ApplicationUser? User { get; private set; }

        public Guid? ElectionId { get; private set; } // Optional FK to an Election, applicable for candidate profile registration.
        public Election? Election { get; private set; } // Navigation property to Election.

        private SystemAuditLog() 
        {}

        // --- Factory Method ---

        /// <summary>
        /// Creates a new SystemAuditLog instance to record an administrative action.
        /// </summary>
        /// <param name="userId">The ID of the user performing the action.</param>
        /// <param name="actionType">The specific type of action being logged.</param> // CHANGED
        /// <param name="details">Optional, detailed information about the action (e.g., JSON of the changed data).</param>
        /// <returns>A new, valid SystemAuditLog object.</returns>
        /// <exception cref="ArgumentException">Thrown if validation fails.</exception>
        public static SystemAuditLog Create(Guid userId, SystemActionTypesEnum actionType, string? details,Guid? electionId) 
        {
            Validate(userId, actionType);
            
            if(actionType == SystemActionTypesEnum.CANDIDATE_PROFILE_CREATED && electionId == null)
            {
                throw new ArgumentException("ElectionId is required when logging a CANDIDATE_PROFILE_CREATED action.");
            }

            var logEntry = new SystemAuditLog
            {
                // The 'Id' is generated by the database.
                UserId = userId,
                ActionType = actionType,
                Details = details,
                ElectionId = electionId,
                TimestampUTC = DateTime.UtcNow
            };

            return logEntry;
        }

        

        /// <summary>
        /// Private helper method to validate the required parameters.
        /// </summary>
        private static void Validate(Guid userId, SystemActionTypesEnum actionType) // CHANGED: Parameter is now an enum
        {
            var errors = new StringBuilder();

            if (userId == Guid.Empty)
            {
                errors.AppendLine("UserId is required for the audit log entry.");
            }

            // CHANGED: Validation now checks if the enum value is a defined member.
            if (!Enum.IsDefined(typeof(SystemActionTypesEnum), actionType))
            {
                errors.AppendLine("A valid ActionType is required for the audit log entry.");
            }

            if (errors.Length > 0)
            {
                throw new ArgumentException(errors.ToString());
            }
        }
    }
}