namespace GovernmentSystem.API.Application.RequestDTOs.CandidateDTOs
{
    public class CreateCandidateRequestDTO
    {   
        public string? NationalId { get; set; }

        // id is auto-generated by the database, so it should not be included in the request DTO
        // citizenId is queried based on nationalId, so it should not be included in the request DTO
        // nominationToken and hash are also auto-generated by the system, so they should not be included in the request DTO

    }
}