using GovernmentSystem.API.Domain.Enums;

namespace GovernmentSystem.API.Application.RequestDTOs.CitizenDTOs
{
    public class CreateCitizenRequestDTO
    {
        // id - nationalId are autogenerated by the system, so they are not included in the request DTO
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public DateOnly? DateOfBirth { get; set; }

        public GovernorateIdEnum? Governorate { get; set; }

        public char? Gender { get; set; }
    }
}